# Specify the virtual environment
dist: trusty
sudo: true


# Specify the project language and the compiler to test to
language: cpp
compiler: gcc


# Enable Slack notifications, disable e-mail
notifications:
    email: false


# Before installing, we need a never version of CMake.
before_install:
  #   Travis CI's CMake version is only 3.2.2.
  #   This is a workaround that upgrades to a newer version of CMake.
  #   Credits to (https://github.com/travis-ci/travis-ci/issues/7437)
  - mkdir ${HOME}/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh
  - chmod +x cmake-3.9.1-Linux-x86_64.sh
  - ./cmake-3.9.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license


# Run the build script
script:
  - cd /home/travis/build/lelemmen/numopt
  - mkdir build && cd build
  - cmake ..
  - make && make test && sudo make install
