# Specify the virtual environment
dist: trusty
sudo: true


# Specify the project language and the compiler to test to
language: cpp
compiler: gcc


# Enable Slack notifications, disable e-mail
notifications:
    slack: gqcg:5PZ5ibXCwNU1b5ToWbHVIqnI
    email: false


# Before installing, we need a never version of CMake.
before_install:
  #   Travis CI's CMake version is only 3.2.2.
  #   This is a workaround that upgrades to a newer version of CMake.
  #   Credits to (https://github.com/travis-ci/travis-ci/issues/7437)
  - mkdir ${HOME}/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh
  - chmod +x cmake-3.9.1-Linux-x86_64.sh
  - ./cmake-3.9.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license


# Install dependencies
install:

  # We need a recent version of Eigen3, but this is not available through APT.
  - mkdir /tmp/eigen && cd /tmp/eigen
  - curl -OL "http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2"
  - tar --bzip2 -xf 3.3.4.tar.bz2
  - mkdir /tmp/build-eigen && cd /tmp/build-eigen
  - cmake . /tmp/eigen/eigen-eigen-5a0156e40feb
  - make && sudo make install


  # We need relatively recent boost libraries, and APT doesn't provide these.
  - mkdir /tmp/boost && cd /tmp/boost
  - curl -OL "https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2"
  - cd /usr/local/
  - sudo tar --bzip2 -xf /tmp/boost/boost_1_65_1.tar.bz2
  - export BOOST_ROOT=/usr/local/boost_1_65_1


  # Install the cpputil library
  - mkdir /tmp/cpputil && cd /tmp/cpputil
  - git clone https://github.com/GQCG/cpputil.git --branch master --single-branch
  - cd cpputil
  - mkdir build && cd build
  - cmake .. && make && make test && sudo make install


  # Install Spectra
  - cd /usr/local/
  - git clone https://github.com/yixuan/spectra.git



# Run the build script
script:
  - cd /home/travis/build/GQCG/numopt
  - mkdir build && cd build
  - cmake ..
  - make && make test && sudo make install
